### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by AlexSokokoliuk** [sousasag/ARES#10]
Hi! I have some troubles with launching ARES software. 
This is an output of program (When I'm launching ./ARES in the bash):
```
Input Parameters:

specfits: fdsfsdfs.fits
readlinedat: WDLines.dat
fileout: test.ares
lambdai: 3808.0
lambdaf: 9191.0
smoothder: 4.0
space: 3.00 
rejt: 0.995

lineresol: 0.100
miniline: 2.0
plots_flag: 0
Segmentation fault (core dumped)
```
This is my mine.opt:
```
specfits='fdsfsdfs.fits'
readlinedat='WDLines.dat'
fileout='test.ares'
lambdai=3808.
lambdaf=9191.
smoothder=4
space=3.0
rejt=0.995
lineresol=0.1
miniline=2
plots_flag=0
```
And this is my line data file:
```
Wavelenght    Element name
----------------------------------------------------------------------------------------------------------------
1215 Ly alpha
1240 N V
1549 C IV
1640 He II
1908 C III
2799 Mg II
3725 O II
3727 O II
3868 Ne III
3890 H epsilon
3970 Ne III
4102 H delta
4341 H gamma
4363 O III
4685 He II
4862 H beta
4959 O III
5007 O III 
5411 He II
5577 O I
6300 O I
6312 S III
6363 O I
6548 N II
6564 H alpha
6583 N II
6716 S II
6730 S II
7135 Ar III
```
And finally this is beginning of my 1D SDSS DR16 spectra file:
```
   7.715205E+01
   7.683772E+01
   7.997759E+01
   8.035571E+01
   8.762325E+01
   8.818520E+01
   8.401875E+01
   8.346867E+01
```

**Comment by sousasag** [comment]
Hi,

Best would be for you to share your spectra file so I can try to reproduce the issue.
I see some possible problems in your input:
1- Your linedata seems to have only integer numbers, and close you have some chars of the element of each line.

Try to do something like:

```
Wavelenght    Element name
----------------------------------------------------------------------------------------------------------------
1215.00        Ly alpha
1240.00        N V
1549.00        C IV
1640.00       He II
1908.00       C III
2799.00       Mg II
```
...

2- Be sure that the units of your wavelength in the spectra is in Angstroms.

If you share your spectra I can try to reproduce the problem and try to help you more on this.

**Comment by AlexSokokoliuk** [comment]
[WDSpectrum.txt](https://github.com/sousasag/ARES/files/5791599/WDSpectrum.txt)

**Comment by AlexSokokoliuk** [comment]
This is my spectra flux fits file. https://dropmefiles.com/ViizF
I edited line list file, problem with spectra, because this error appeared: 
``` 
READING FITS FILE: fdsfsdfs.fits 
Ficheiro Aberto...Error: only 1D or 2D images are supported
Cleaning zero gaps
```

**Comment by sousasag** [comment]
Indeed this fits file does not have the "standard" format for ares. ARES reads 1D fits file in the same format as it was done in the splot routine in IRAF.

You need to have one single extension and in the header you need the fits keywords:
CDELT1
CRVAL

Solution:
Reformat your fits spectrum in to the IRAF like which is compatible with ARES.
OR, you can create an ascii file with two columns, wavelenght and flux. ARES can also work with ASCII files
