### ISSUE TITLE
rm: cannot remove 'tmp': No such file or directory

### ISSUE THREAD

**Issue by AlexSokokoliuk** [sousasag/ARES#11]
Hi. I'm sorry for so usual issues reporting, I'm not really good at programming. 
I solved the problem with inputs, but another problem appeared:
```
Input Parameters:

specfits: WDSpectrum.txt
readlinedat: WDLines.dat
fileout: test.ares
lambdai: 3808.0
lambdaf: 9191.0
smoothder: 4.0
space: 3.00 
rejt: 0.995

lineresol: 0.100
miniline: 2.0
plots_flag: 0
File: WDSpectrum.txt
FILE: WDSpectrum.txt
Extension: .txt - 1

 ASCII READ
Cleaning zero gaps
Velocidade radial: 0.000000
ponto 1000, lambda: 53.074710 
ponto 1000, lambda: 53.074710 
Computed rejt: 0.995000 
Rejt used for computations: 0.995000
rm: cannot remove 'tmp': No such file or directory
rm: cannot remove 'tmp2': No such file or directory
rm: cannot remove 'tmp3': No such file or directory
rm: cannot remove 'tmp20': No such file or directory
rm: cannot remove 'tmp22': No such file or directory
rm: cannot remove 'tmp23': No such file or directory

 FINISH. HAVE A GOOD DAY...
```
What should I do now?
Best regards, Alex.

**Comment by sousasag** [comment]
No problem.

These rm are just warnings. The tmp files are there sometimes for ARES plots. When the plots are not asked the code still tries remove these temporary files even if they were not created. I was lazy to fix this warnings...

Having said this, it seems that he did not do any measurements. Did you provide lines to be measured in this run?

Btw, WDspectrum, is this a spectrum from a White Dwarf? Are there week lines as in solar-type stars? ARES is OK to measure week lines [5mA-200mA].

**Comment by AlexSokokoliuk** [comment]
Yes, the spectrum is from White Dwarf.
How can I provide what lines i want to be measured?

**Comment by AlexSokokoliuk** [comment]
Thank you, now all is ok.
