### ISSUE TITLE
gsl: interp.c:168: ERROR: interpolation error

### ISSUE THREAD

**Issue by AlexSokokoliuk** [sousasag/ARES#12]
Hi. It's me again. Now I've analyzed M dwarf spectra (NIR Ca II Triplet).
My mine.opt:
```
specfits='Mstar.txt'
readlinedat='Mlines.txt'
fileout='test.ares'
lambdai=3805
lambdaf=9206
smoothder=4
space=100
rejt=2;8090,8165,8806,8851
lineresol=0.1
miniline=2
plots_flag=0
```
Beginning of my specfits file:
```
3805,39725	1,326547
3806,273576	8,486364E-01
3807,150104	5,947203
3808,026833	8,314162E-01
3808,903765	-6,742182E-01
3809,780898	1,145224
3810,658234	6,326815E-01
3811,535771	-1,043438
3812,413511	-9,656579E-01
3813,291453	8,975424E-02
3814,169597	7,128929E-01
3815,047943	3,0283
3815,926491	5,585159
3816,805242	4,957308E-01
3817,684195	-6,151395
3818,56335	-1,023792
3819,442708	1,040876
3820,322269	-3,700753E-01
3821,202032	1,128262
```
My lines data:
```
Wavelenght           Name
--------------------------------------------------------------------------------------------------------------
8498 Ca II 
8542 Ca II 
8662 Ca II 
```
I'm really sorry for for such frequent contact to you.
Your code is very beautiful.
Best regards, Alex.

**Comment by DanielAndreasen** [comment]
Just out of curiosity, have you tried to plot your spectrum? It seems strange that you have negative flux values. And I could also imagine the decimal point should be a `.` rather than a `,`.

**Comment by AlexSokokoliuk** [comment]
I rewrote the flux with `.` and added `.00` to lines data, but problem still appearing.
That's my spectrum:
![powGraph](https://user-images.githubusercontent.com/76453303/104881161-7ee05000-5969-11eb-8ed5-f187d44a5f23.jpg)

**Comment by sousasag** [comment]
Hi,
I can read very well your plotted spectrum. Is it going to 8000-9000A???
If not, that may be the problem for rejt.

Also, again, ARES is for solar-type stars spectra, For M stars it will not work very well. Well it will work as bad as you would do it interactively marking the continuum and guessing the lines to fit... In M stars the real continuum is very difficult to find...

**Comment by AlexSokokoliuk** [comment]
I solved the problem. Thanks.
