### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by veronicaloatac** [sousasag/ARES#9]
Dear Sergio

I have been testing the readme examples following your tutorial (youtube-movie) using the different entries in the mine.opt file, and executing ./ARES, in all cases, I get the following error:

mine.opt
number of options: 11
Segmentation fault (core dumped)

**Comment by sousasag** [comment]
Hi,

You need to me a bit more specific. Can you share the contents of your mine.opt file, And the input files so I can try to reproduce the problem?

**Comment by veronicaloatac** [comment]
Hi Sergio,

The contents of the mine.opt file is:

specfits='sun_harps_ganymede.fits'
readlinedat='linelist.dat'
fileout='sun_harps_ganymede.crime'
lambdai=3600.
lambdaf=9000.
smoothder=4
space=3.0
rejt=0.995
lineresol=0.1
miniline=2
plots_flag=0

and another mine.opt file that I tested is:

specfits='sun_harps_ganymede.fits'
readlinedat='linelist.dat'
fileout='sun_harps_ganymede.crime'
lambdai=3600.
lambdaf=9000.
smoothder=4
space=3.0
rejt=3;5764,5766,6047,6053,6068,6076
lineresol=0.1
miniline=2
plots_flag=1
rvmask='3,6021.8,6024.06,6027.06,6024.06,20'

in both cases the result after run ./ARES is:
      mine.opt
      number of options: 11
      Segmentation fault (core dumped)

Thanks for the help

**Comment by sousasag** [comment]
Hi,

I am not able to reproduce your problem. It works well in my computer in both cases...

Can you do a make clean and make install?
Maybe is something related with your compilation?
How did you compiled, was there any errors/warnings in the compilation?

**Comment by veronicaloatac** [comment]
Hi Sergio,

I reinstalled and now it is working.

Thanks so much
